# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Novel visual computations
baseurl: https://laurentperrinet.github.io/
copyright: 'This material is presented to ensure timely dissemination of scholarly
  and technical work. Copyright and all rights therein are retained by authors or
  by other copyright holders. All persons copying this information are expected to
  adhere to the terms and constraints invoked by each author''s copyright. In most
  cases, these works may not be reposted without the explicit permission of the copyright
  holder.

  <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative
  Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png"
  /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative
  Commons Attribution-Noncommercial-Share Alike 3.0 Unported License</a>

  Please note that multiple distribution, publication or commercial usage of copyrighted
  papers included in this website would require submission of a permission request
  addressed to the journal in which the paper appeared.
  '

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 100
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
# https://gohugo.io/content-management/urls/#permalink-configuration-values
permalinks:
  event: '/talk/:filename/'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  #home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  home: [HTML, RSS, JSON]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
