<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception</s:exception>
  <s:message>An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`, `lock`, `ttl`) VALUES(?, ?, ?)' with params ["files\/852d2823b987d1419f438bbc974dfb15", 1, 1599734304]:

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction</s:message>
</d:error>
s"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
